### PR TITLE
Update Riak.Search to work with pooler

### PR DESCRIPTION
**Pull request by weixiyen**

### CODE REVIEW

**Comment by weixiyen** [comment]
Keep in mind that there are no tests written for Riak Search, so we can't trust the test checks, but this code does work the same as before.

The first thing to note is that defpool did not work well with default arguments so I created an extra method with different arity.

The second thing to note is defpool caused function naming collision with the Erlang client's protobuf socket library's **put** method due to method names and arity being the same, so I excluded all the :riakc_pb_socket **put** related methods from the import.

**Comment by edgurgel** [comment]
I wonder if we can add some tests to riak search module. I'm not sure if Travis supports this :/

**Comment by hansonkd** [comment]
I was just about to write this! Definitely would make the library more congruent.

**Comment by hansonkd** [comment]
Also while we are at it, I believe the argument names are incorrect. We are not passing in bucket names, but rather index names. 

riakc function signature is this:

    create_search_index(Pid::pid(), Index::binary()) -> ok

This tripped me up when I first came across it, since I thought it was an interface for adding a search index to a bucket's props.

**Comment by drewkerrigan** [comment]
6fa419b LGTM, any issues with merging this @edgurgel ?

**Comment by edgurgel** [comment]
LGTM! :thumbsup:

**Pull request merged**
